services:
  node1:
    image: starfwi-test-image
    container_name: starfwi-test-node-1
    hostname: node1
    networks:
      - starfwi-network
    volumes:
      - ./.local_shared_volume:/shared
    stdin_open: true
    tty: true
    command: /bin/bash -c "/usr/sbin/sshd -D"
    cpus: 2
    mem_limit: 6g

  node2:
    image: starfwi-test-image
    container_name: starfwi-test-node-2
    hostname: node2
    networks:
      - starfwi-network
    volumes:
      - ./.local_shared_volume:/shared
    stdin_open: true
    tty: true
    command: /bin/bash -c "/usr/sbin/sshd -D"
    cpus: 3
    mem_limit: 6g

  starvz-shell:
    image: starvz-shell
    container_name: starvz-shell
    volumes:
      - ./.local_shared_volume:/shared
    stdin_open: true
    tty: true

networks:
  starfwi-network:
    driver: bridge
